# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
# edited by phossil
# 2022-12-15
# MSI B450 Gaming Plus Max

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/fdf75b59-4641-48db-9f68-d886afd88cab";
    fsType = "ext4";
    # performance tuning for ext4
    options = [
      "defaults"
      "lazytime"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/375B-9826";
    fsType = "vfat";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/12e7a0c4-fced-486f-93ee-a72b7b0b8a36";
    fsType = "f2fs";
    # pls check the arch wiki's page on f2fs
    options = [
      "defaults"
      "compress_algorithm=zstd:6"
      "compress_chksum"
      "atgc"
      "gc_merge"
      "lazytime"
    ];
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/34c9ad59-f3b9-4f92-91d3-b29d03879b45"; }];

  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
