# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
# edited by phossil
# 2022-12-24
# MSI B450 Gaming Plus Max

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ed1a772f-1145-4091-9cc4-2395b9dd66ea";
    fsType = "f2fs";
    # pls check the arch wiki's page on f2fs
    options = [
      "defaults"
      "compress_algorithm=zstd:6"
      "compress_chksum"
      "atgc"
      "gc_merge"
      "lazytime"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/23DA-C4BB";
    fsType = "vfat";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/12e7a0c4-fced-486f-93ee-a72b7b0b8a36";
    fsType = "f2fs";
    # pls check the arch wiki's page on f2fs
    options = [
      "defaults"
      "compress_algorithm=zstd:6"
      "compress_chksum"
      "atgc"
      "gc_merge"
      "lazytime"
    ];
  };

  swapDevices =
    [
      { device = "/dev/disk/by-uuid/34c9ad59-f3b9-4f92-91d3-b29d03879b45"; }
      # huge swap for hibernation
      { device = "/dev/disk/by-uuid/ff5b096e-6dbf-42ce-b795-62ed9eada908"; }
    ];

  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
