# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ehci_pci"
    "ahci"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/6a1a08bf-bdeb-4d25-94a6-76aa36c70905";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2DCC-479C";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/6a1a08bf-bdeb-4d25-94a6-76aa36c70905";
    fsType = "btrfs";
    options = [ "subvol=@home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/6a1a08bf-bdeb-4d25-94a6-76aa36c70905";
    fsType = "btrfs";
    options = [ "subvol=@nix" ];
  };

  fileSystems."/root" = {
    device = "/dev/disk/by-uuid/6a1a08bf-bdeb-4d25-94a6-76aa36c70905";
    fsType = "btrfs";
    options = [ "subvol=@root" ];
  };

  fileSystems."/srv" = {
    device = "/dev/disk/by-uuid/6a1a08bf-bdeb-4d25-94a6-76aa36c70905";
    fsType = "btrfs";
    options = [ "subvol=@srv" ];
  };

  fileSystems."/var/cache" = {
    device = "/dev/disk/by-uuid/6a1a08bf-bdeb-4d25-94a6-76aa36c70905";
    fsType = "btrfs";
    options = [ "subvol=@cache" ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/6a1a08bf-bdeb-4d25-94a6-76aa36c70905";
    fsType = "btrfs";
    options = [ "subvol=@log" ];
  };

  fileSystems."/var/tmp" = {
    device = "/dev/disk/by-uuid/6a1a08bf-bdeb-4d25-94a6-76aa36c70905";
    fsType = "btrfs";
    options = [ "subvol=@tmp" ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/8d424dff-ae1b-498e-93d5-0d6160045d25"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
